In [2]:
# merging jioning and concatination
import pandas as pd
import numpy as np

In [1]:
data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}

data2 = {'Name': ['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
         'Age': [17, 14, 12, 52],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']}

In [4]:
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2,index=[4, 5, 6, 7])

In [5]:
print(df1)
print("dataframe 2 is\n ", df2)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
dataframe 2 is
       Name  Age    Address Qualification
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [6]:
df3 = [df1 , df2]
print(pd.concat(df3))

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [7]:
data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd'],
         'Mobile No': [97, 91, 58, 76]}

data2 = {'Name': ['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
         'Age': [22, 32, 12, 52],
         'Address': ['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
         'Qualification': ['MCA', 'Phd', 'Bcom', 'B.hons'],
         'Salary': [1000, 2000, 3000, 4000]}

df = pd.DataFrame(data1, index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[2, 3, 6, 7])


res1 = pd.concat([df,df1],axis=1,join='inner')
res2 = pd.concat([df,df1],axis=1,sort=False)
res3 = pd.concat([df,df1],axis=0,join='inner')

In [8]:
print(res1)

     Name  Age    Address Qualification  Mobile No    Name  Age    Address  \
2  Gaurav   22  Allahabad           MCA         58  Gaurav   22  Allahabad
3    Anuj   32    Kannuaj           Phd         76    Anuj   32    Kannuaj

  Qualification  Salary
2           MCA    1000
3           Phd    2000

In [9]:
print(res2)

     Name   Age    Address Qualification  Mobile No    Name   Age    Address  \
0     Jai  27.0     Nagpur           Msc       97.0     NaN   NaN        NaN
1  Princi  24.0     Kanpur            MA       91.0     NaN   NaN        NaN
2  Gaurav  22.0  Allahabad           MCA       58.0  Gaurav  22.0  Allahabad
3    Anuj  32.0    Kannuaj           Phd       76.0    Anuj  32.0    Kannuaj
6     NaN   NaN        NaN           NaN        NaN  Dhiraj  12.0  Allahabad
7     NaN   NaN        NaN           NaN        NaN  Hitesh  52.0    Kannuaj

  Qualification  Salary
0           NaN     NaN
1           NaN     NaN
2           MCA  1000.0
3           Phd  2000.0
6          Bcom  3000.0
7        B.hons  4000.0

In [10]:
print(res3)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [11]:
frames = [df, df1 ]

res = pd.concat(frames, keys=['x', 'y'])
res

       Name  Age    Address Qualification  Mobile No  Salary
x 0     Jai   27     Nagpur           Msc       97.0     NaN
  1  Princi   24     Kanpur            MA       91.0     NaN
  2  Gaurav   22  Allahabad           MCA       58.0     NaN
  3    Anuj   32    Kannuaj           Phd       76.0     NaN
y 2  Gaurav   22  Allahabad           MCA        NaN  1000.0
  3    Anuj   32    Kannuaj           Phd        NaN  2000.0
  6  Dhiraj   12  Allahabad          Bcom        NaN  3000.0
  7  Hitesh   52    Kannuaj        B.hons        NaN  4000.0

In [12]:
import pandas as pd
gf = pd.read_csv("https://media.geeksforgeeks.org/wp-content/uploads/nba.csv")

In [13]:
gf

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
team = gf.groupby('Team').agg()
print(team.first())

TypeError: Must provide 'func' or tuples of '(column, aggfunc).

In [ ]:
gf

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.flipud(array,))

[[7 8 9]
 [4 5 6]
 [1 2 3]]